name: "lint"

on:
  workflow_call:
  pull_request_target:
    branches: [main]
    types: [opened, synchronize]

concurrency:
  group: lint-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@cd2651c46231bc0d6f48d6b34433b845331235fe # v5.0.0
        with:
          node-version-file: "package.json"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run check
        run: npm run lint
