name: "semantic / release"

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml
  test:
    uses: ./.github/workflows/test.yml
  please:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      # Build and upload to stores still needs to be done manually for now
      - uses: googleapis/release-please-action@3612a99d75bd7a010bb03d6e2ee3e2392b7392fb # v4.2.0
        id: release
        with:
          config-file: release.json
          manifest-file: .release-manifest.json
